#!/usr/bin/env bash
set -euo pipefail

name="mergesubs"
version="v1.0.0"

function print_help {
  cat <<EOF
NAME
  ${name} - combine video and subtitles

SYNOPSIS
  ${0} <name>

DESCRIPTION
  Given a matching name of a video and subtitles file, creates an MKV with the
  same name containing both.

  Version:   ${version}
  Homepage:  https://github.com/jahed/${name}
  Donate:    https://jahed.dev/donate

OPTIONS
  <name>
    The name of the video and subtitles file.

  -h, --help
    Prints this help message.

  --version
    Prints the version.

DEPENDENCIES
  Required
    ffmpeg  https://ffmpeg.org/

COPYRIGHT
  Copyright (C) 2020 Jahed Ahmed

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
EOF
}

function failure {
  echo "error:        ${1}"
  echo "for help use: ${0} --help"
  exit 1
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      print_help
      exit 0
      ;;
    --version)
      echo "${name} ${version}"
      exit 0
      ;;
    -*)
      failure "unknown argument $1"
      exit 1
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done
set -- "${POSITIONAL[@]}"

if [[ ! -f "${1}.mp4" ]]; then
   failure "video file not found"
   exit 1
fi

if [[ ! -f "${1}.srt" ]]; then
  failure "subtitle file not found"
  exit 1
fi

echo
echo 'MERGING'

ffmpeg \
  -i "${1}.mp4" \
  -i "${1}.srt" \
  -map 0 \
  -map 1 \
  -c copy \
  -metadata:s:s:0 language=eng \
  "${1}.mkv"

echo
echo "RESULT"
echo "  ${1}.mkv"

echo
echo 'Done.'

